name: Auto Merge PRs

on:
  schedule:
    # 8:32 PM IST ke liye UTC time 3:02 PM hota hai.
    - cron: '2 15 * * *'

jobs:
  merge-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Fetch and Merge PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # <aapka-username> ko apne GitHub username se replace karein
          gh pr list --repo <aapka-username>/digital-ERP --state open --json number -q '.[].number' | xargs -r -I % gh pr merge % --auto --merge
